// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, spawn;

  express = require('express');

  spawn = require('child_process').spawn;

  app = express();

  app.get('/:command/:arg/:zone?', function(req, res) {
    var command, onkyo, params, zone;

    params = req.params;
    zone = params.zone || 'main.';
    command = zone + params.command + '=' + params.arg;
    onkyo = spawn('/usr/local/bin/onkyo', ['--all', command]);
    onkyo.stdout.on('data', function(data) {
      return res.send('stdout: ' + data);
    });
    return onkyo.stderr.on('data', function(data) {
      return res.send('stderr: ' + data);
    });
  });

  app.get('/', function(req, res) {
    return res.send('hello onkyo');
  });

  app.listen(3000);

}).call(this);
