// Generated by CoffeeScript 1.6.3
var app, express, spawn;

express = require('express');

spawn = require('child_process').spawn;

app = express();

app.get('/:command/:arg/:zone?', function(req, res) {
  var command, onkyo, params, zone;
  params = req.params;
  zone = params.zone || 'main.';
  command = zone + params.command + '=' + params.arg;
  onkyo = spawn('/usr/local/bin/onkyo', ['--all', command]);
  return onkyo.stdout.on('data', function(data) {
    return res.send(data);
  });
});

app.get('/', function(req, res) {
  return res.send('hello onkyo');
});

app.listen(3000);

/*
//@ sourceMappingURL=app.map
*/
